rpc_url = "http://127.0.0.1:9091/transmission/rpc"
rpc_user = "none"
rpc_pass = "none"
force_not_remote = false
base_dir = "/var/cache/torrents/"
sqlitedb = true
verify = false
dldirs = ["/var/cache/torrents/dl"]
ask_existing = true
copydir = "none"
quota_per_dldir = "100 GiB"
free_space_per_dldir = "100 GiB"
dst_free_space_to_leave = "40 GiB"
color = "none"
